project_id = "vmzxpqztavxabwsiisau"

[functions.admin-delete-user]
verify_jwt = false

[functions.admin-set-password]
verify_jwt = false

[functions.admin-user-suspend]
verify_jwt = false

[functions.validate-access-code]
verify_jwt = false

[functions.decrement-access-code]
verify_jwt = false
